#
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: rafael_devl

test:
  <<: *default
  database: rafael_test

production:
  <<: *default
  database: rafael_prod
